proveedor:
    resource: "@ProveedorBundle/Resources/config/routing.yml"
    prefix:   /

comun:
    resource: "@ComunBundle/Resources/config/routing.yml"
    prefix:   /

emision_garantia:
    resource: "@emisionGarantiaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
