emision_garantia_homepage:
    path:     /hello/{name}
    defaults: { _controller: emisionGarantiaBundle:Default:index }
   
prueba_garantia_homepage:
    path:     /web
    defaults: { _controller: emisionGarantiaBundle:Default:pagina }
